# The time at which sudden death is scheduled to start unix time
sudden-death-start:

# Remaining time in millis in sudden death for team disbanding
sudden-death-team-disband-time: 900000

# Amount of millis which sudden death border should shrink over
sudden-death-length: 1800000

# The default size of the worldborder
default-border-size: 5000

# Final world border size
border-size: 10

# Min amount of ticks which a drop takes to fall
drop-mix-ticks: 4800

# Max amount of ticks which a drop takes to fall
drop-max-ticks: 7201

# Enable end crystal explosions
end-crystals: false

# Enable respawn anchors explosions
respawn-anchors: false

# Should the logic death by environment/mobs keep inventory and not if killed by another player (Turning this of means the server will use the vanilla gamerule IF TURNED ON MAKE SURE THE GAMERULE IS SET TO FALSE)
keep-inventory-management: true

# Amount of time after being attacked by a player in which a death all be counted as a death by a player (Millis) Used by the keep inventory system
combat-tag-time: 15000

# Commands disabled in sudden death
sudden-death-disabled-commands:
  - "/sethome"
  - "/home"
  - "/delhome"
  - "/listhome"
  - "/renamehome"
  - "/relocatehome"
  - "/spawn"
  - "/tpa"
  - "/tpaccept"
  - "/tpdeny"
  - "/team sethome"
  - "/team setwarp"
  - "/team home"
  - "/team warp"
  - "/team warps"

no-teams-disabled-commands:
  - "/team"