# The time at which sudden death is scheduled to start unix time
sudden-death-start:

# Remaining time in millis in sudden death for team disbanding
sudden-death-team-disband-time: 900000

# Amount of millis which sudden death boarder should shrink over
sudden-death-length: 1800000

# Final world boarder size
boarder-size: 10

# Min amount of ticks which a drop takes to fall
drop-mix-ticks: 4800

# Max amount of ticks which a drop takes to fall
drop-max-ticks: 7201

# Enable end crystal explosions
end-crystals: false

# Enable respawn anchors explosions
respawn-anchors: false

# Commands disabled in sudden death
sudden-death-disabled-commands:
  - "/sethome"
  - "/home"
  - "/delhome"
  - "/listhome"
  - "/renamehome"
  - "/relocatehome"
  - "/spawn"
  - "/tpa"
  - "/tpaccept"
  - "/tpdeny"
  - "/team sethome"
  - "/team setwarp"
  - "/team home"
  - "/team warp"
  - "/team warps"

no-teams-disabled-commands:
  - "/team"