# The Unix timestamp in seconds at which sudden death is scheduled to start
sudden-death-start:

# Time in seconds before teams disband during sudden death
sudden-death-team-disband-time: 900

# Time in seconds for the sudden death border to shrink
sudden-death-length: 1800

# Is spawn command enabled
spawn-enabled: true

# The default size of the worldborder
default-border-size: 5000

# Final world border size
border-size: 10

# Show drop timetable link on join the server
show-drop-timetable: false

# The drop timetable link
drop-timetable-link:

# Min amount of ticks which a drop takes to fall
drop-mix-ticks: 4800

# Max amount of ticks which a drop takes to fall
drop-max-ticks: 7201

# Damage effect balancing systems
# Enables or disables the entire damage balancing system.
damage-balance-enabled: true

# The neutral K/D difference range before any balance modifier starts.
damage-balance-effects-zero-range: 5

# How many additional net kills/deaths are required for each balance level.
damage-balance-effects-multiplier: 2

# Maximum balance level that can be applied.
# Prevents the damage bonus/penalty from increasing indefinitely.
damage-balance-effects-max-level: 5

# Percentage damage change applied per balance level.
# 0.10 = 10% per level
damage-balance-damage-per-level: 0.10

# Enable end crystal explosions
end-crystal-entity-damage: false
end-crystal-block-damage: false

# Enable respawn anchors explosions
respawn-anchors-explode: false

# Maximum number of homes a player can create without the unlimited permission
max-homes: 3

# Delay in seconds before TeleportHelper teleports a player
teleport-delay: 5

# Should the logic death by environment/mobs keep inventory and not if killed by another player (Turning this of means the server will use the vanilla gamerule IF TURNED ON MAKE SURE THE GAMERULE IS SET TO FALSE)
keep-inventory-management: true

# Broadcast keep inventory force-enable state changes and warnings
keep-inventory-force-alerts: true

# Warn this many ticks before keep inventory force-enable turns off
keep-inventory-force-warning-ticks: 1200

# How long a drop force-enables keep inventory for
drop-keep-inventory-force-duration-ticks: 12000

# Time in seconds after a player attack during which a death counts as a player kill
combat-tag-time: 15

# Commands disabled in sudden death
sudden-death-disabled-commands:
  - "/sethome"
  - "/home"
  - "/delhome"
  - "/listhome"
  - "/renamehome"
  - "/relocatehome"
  - "/spawn"
  - "/tpa"
  - "/tpaccept"
  - "/tpdeny"
  - "/team sethome"
  - "/team setwarp"
  - "/team home"
  - "/team warp"
  - "/team warps"

no-teams-disabled-commands:
  - "/team"

drop-disabled-commands:
