name: MMBattlegrounds
version: '${version}'

main: com.github.minemaniauk.MMBattlegrounds.MMBattlegrounds
api-version: '26.1'
depend:
  - FastAsyncWorldEdit
softDepend:
  - BetterTeams
  - HomePlugin
commands:
  startsuddendeath:
    permission: "mmbattlegrounds.suddendeath.start"
  dropcreate:
    permission: "mmbattlegrounds.drop.create"
  dropremove:
    permission: "mmbattlegrounds.drop.remove"
  dropselect:
    permission: "mmbattlegrounds.drop.select"
  dropsetitems:
    permission: "mmbattlegrounds.drop.set.items"
  dropsetlocation:
    permission: "mmbattlegrounds.drop.set.location"
  dropspawn:
    permission: "mmbattlegrounds.drop.spawn"
  resetallborders:
    permission: "minecraft.command.worldborder"

permissions:
  mmbattlegrounds.bypass.commanddisablement:
    description: Allows bypassing disabled command restrictions
    default: op
  mmbattlegrounds.suddendeath.start:
    description: Allows executing the sudden death start command
    default: op
  mmbattlegrounds.drop.create:
    description: Allows creating a new drop entry
    default: op
  mmbattlegrounds.drop.remove:
      description: Allows removing an existing drop entry
      default: op
  mmbattlegrounds.drop.set.items:
    description: Allows setting the items in a drop entry
    default: op
  mmbattlegrounds.drop.set.location:
    description: Allows setting the location of a drop entry
    default: op
  mmbattlegrounds.drop.spawn:
    description: Allows spawning a drop entry into the world
    default: op